In [1]:
import numpy as np
import builtins

def print(*args):
    return builtins.print(*args, sep='\n', end='\n\n')

mat1 = np.random.randint(low=1, high=10, size=(3,3))
mat2 = np.random.randint(low=10, high=20, size=(3,3))
print('mat1:', mat1)
print('mat2:', mat2)

mat1:
[[2 4 2]
 [2 1 5]
 [5 7 2]]

mat2:
[[13 15 11]
 [19 11 10]
 [15 13 11]]



### Addition d'arrays

In [2]:
print('mat1 + mat2:', mat1 + mat2)
print('np.add(mat1, mat2):', np.add(mat1, mat2))

mat1 + mat2:
[[15 19 13]
 [21 12 15]
 [20 20 13]]

np.add(mat1, mat2):
[[15 19 13]
 [21 12 15]
 [20 20 13]]



### Soustraction d'arrays

In [5]:
print('mat1 - mat2:', mat1 - mat2)
print('np.subtract(mat1, mat2):', np.subtract(mat1, mat2))

mat1 - mat2:
[[-11 -11  -9]
 [-17 -10  -5]
 [-10  -6  -9]]

np.subtract(mat1, mat2):
[[-11 -11  -9]
 [-17 -10  -5]
 [-10  -6  -9]]



In [11]:
mat3 = np.random.randint(low=1, high=10, size=(3,2))
mat4 = np.random.randint(low=10, high=20, size=(2,3))
print('mat3:', mat3)
print('mat4:', mat4)

mat3:
[[4 2]
 [6 3]
 [3 4]]

mat4:
[[11 18 13]
 [19 10 15]]



### Produit de matrices

In [10]:
print('np.matmul(mat3, mat4):', np.matmul(mat3, mat4))
print('np.dot(mat3, mat4):', np.dot(mat3, mat4))
print('np.matmul(mat4, mat3):', np.matmul(mat4, mat3))
print('np.dot(mat4, mat3):', np.dot(mat4, mat3))

np.matmul(mat3, mat4):
[[ 61  70  62]
 [114 160 128]
 [109 128 112]]

np.dot(mat3, mat4):
[[ 61  70  62]
 [114 160 128]
 [109 128 112]]

np.matmul(mat4, mat3):
[[123 170]
 [132 210]]

np.dot(mat4, mat3):
[[123 170]
 [132 210]]

